### ISSUE TITLE
Blank page in PDF

### ISSUE THREAD

**Issue by marianoibaldi** [biostats-r/quartothesis#1]
After the cover and the table of contents, the resulting PDF has its first page in blank. Also, this first page appears in the table of contents as a blank item but with page number assigned.

I think this is produced by the first chunk of code in the index file (when I set the *echo* option to 'true', it appears in the original blank page).

I tried to eliminate the problem, setting *include* to 'false', but did not work.

![toc_capture](https://user-images.githubusercontent.com/95048061/184317297-60282844-fd34-4d40-98d1-3e64fab21547.png)

**Comment by richardjtelford** [comment]
This used to work...

If you are only interested in the PDF, replace the contents of index.qmd with the acknowledgements and delete acknowledgements.qmd from the _quarto.yml

If you want both html and pdf - I'll get back to you on that.

**Comment by richardjtelford** [comment]
See this issue https://github.com/quarto-dev/quarto-cli/issues/1108

**Comment by marianoibaldi** [comment]
Many thanks for both answers!
